version: '3'

services:
  app:
    build:
      context: .
    command: npm run start-dev
    volumes:
      - "./src/:/ts-api/src"
    ports:
      - "9229:9229"
      - "3000:3000"

  db:
    ports:
      - "27018:27017"

  test:
    command: npm run test-integration-dev
    volumes:
      - "./test/:/ts-api/test"