version: '3'

volumes:
  db-data:
    driver: local

services:
  app:
    image: ts-api:latest
    command: npm run start
    depends_on:
      - db

  db:
    image: mongo:3.6
    volumes:
      - "db-data:/data/db"

  test:
    image: ts-api:latest
    command: npm run test-integration
    depends_on:
      - db
      - app
      